# -*- coding: utf-8 -*-
"""Numpy-demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pvIi17N4FPT4Kq7eYec8LstOJ1101mN2
"""

import numpy as np



#declare array
f_array=np.array([1,2,3,4])
f_array

#array with zeroes
z_array=np.zeros((3,3))
z_array

#array with ones
o_array=np.ones((3,3))
o_array

#empty array
e_array=np.empty((2,3))
e_array

#arange method
np_arange=np.arange(12)
np_arange

#rearrange
np_arange.reshape(3,4)

#linspace(start,end,number of equidistant numbers)
np_linspace=np.linspace(1,6,5)
np_linspace