# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zVXHsMs7vGgFiZ4r34CG2-rLmWXOdwbD
"""

from sklearn.datasets import load_boston

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
from matplotlib import style
# %matplotlib inline

boston_data=load_boston()

boston_data.DESCR

#define x axis from the data
x_axis=boston_data.data

#define y axis from the data
y_axis=boston_data.target

#plot histogram
style.use('ggplot')
plt.figure(figsize=(7,7))
plt.hist(y_axis,bins=50)
plt.xlabel('price in 1000s USD')
plt.ylabel('number of houses')
plt.show()

style.use('ggplot')
plt.figure(figsize=(7,7))
plt.scatter(boston_data.data[:,5],boston_data.target)
plt.ylabel('price in 1000')
plt.xlabel('number of houses')
plt.show()