# -*- coding: utf-8 -*-
"""webscraping-demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pQ5MkkVh3uq3FVk5mhWKiIFZgOO46rXg
"""

from bs4 import BeautifulSoup, SoupStrainer
import requests

url='http://www.simplilearn.com'

#access the url
result=requests.get(url)

#scrape the webpage
webpage=result.content

#creating a soup object for parsing a webpage
sl_soup=BeautifulSoup(webpage,'html.parser')

result.close()

sl_soup.contents

sl_soup.prettify()

#view head of the soup object
sl_soup.head

sl_soup.title

#find all the links
for link in sl_soup.find_all('a', href=True):
    print(link['href'])